### ISSUE TITLE
Server `acceptClient` timeout parameter not used

### ISSUE THREAD

**Issue by doleron** [elhayra/tcp_server_client#6]
It seems the `int timeout` parameter in:

```c++
Client TcpServer::acceptClient(uint timeout)
```
has no effect because it is not used to setup the `timeval`struct.

It turns out the actual timeout is always 2 secs:

```c++
struct timeval tv;
tv.tv_sec = 2;
tv.tv_usec = 0;
```

**Comment by elhayra** [comment]
Thank you for contributing code to fix this

**Comment by doleron** [comment]
> Thank you for contributing code to fix this

You're welcome!
